# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weather app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather app

  target 'weather appTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 5.4'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'SwiftLocation/Core'
    Pod 'AlomofireImage', '-> 4.1'
  end

  target 'weather appUITests' do
    # Pods for testing
   
  end

end
